spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/groomer
spring.datasource.username=groomer
spring.datasource.password=groomer
app.jwt.secret=web-groomer-dev-secret-key-32chars!!